// Mocks generated by Mockito 5.4.6 from annotations
// in portfolio/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:portfolio/core/utils/result.dart' as _i2;
import 'package:portfolio/feature/blog_post/data/repository/blog_post_repository.dart'
    as _i3;
import 'package:portfolio/feature/blog_post/domain/entity/blog_post.dart'
    as _i8;
import 'package:portfolio/feature/blog_post/domain/usecase/read_all_blog_posts_usecase.dart'
    as _i9;
import 'package:portfolio/feature/career/data/repository/career_repository.dart'
    as _i4;
import 'package:portfolio/feature/career/domain/entity/career.dart' as _i10;
import 'package:portfolio/feature/career/domain/usecase/read_all_careers_usecase.dart'
    as _i11;
import 'package:portfolio/feature/event/data/repository/event_repository.dart'
    as _i5;
import 'package:portfolio/feature/event/domain/entity/event.dart' as _i12;
import 'package:portfolio/feature/event/domain/usecase/read_all_events_usecase.dart'
    as _i13;
import 'package:portfolio/feature/project/data/repository/project_repository.dart'
    as _i6;
import 'package:portfolio/feature/project/domain/entity/project.dart' as _i14;
import 'package:portfolio/feature/project/domain/usecase/read_all_projects_usecase.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlogPostRepository_1 extends _i1.SmartFake
    implements _i3.BlogPostRepository {
  _FakeBlogPostRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCareerRepository_2 extends _i1.SmartFake
    implements _i4.CareerRepository {
  _FakeCareerRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventRepository_3 extends _i1.SmartFake
    implements _i5.EventRepository {
  _FakeEventRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProjectRepository_4 extends _i1.SmartFake
    implements _i6.ProjectRepository {
  _FakeProjectRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BlogPostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlogPostRepository extends _i1.Mock
    implements _i3.BlogPostRepository {
  MockBlogPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Result<List<_i8.BlogPost>>> readAllBlogPosts() =>
      (super.noSuchMethod(
        Invocation.method(
          #readAllBlogPosts,
          [],
        ),
        returnValue: _i7.Future<_i2.Result<List<_i8.BlogPost>>>.value(
            _FakeResult_0<List<_i8.BlogPost>>(
          this,
          Invocation.method(
            #readAllBlogPosts,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Result<List<_i8.BlogPost>>>);
}

/// A class which mocks [ReadAllBlogPostsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadAllBlogPostsUseCase extends _i1.Mock
    implements _i9.ReadAllBlogPostsUseCase {
  MockReadAllBlogPostsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.BlogPostRepository get blogPostRepository => (super.noSuchMethod(
        Invocation.getter(#blogPostRepository),
        returnValue: _FakeBlogPostRepository_1(
          this,
          Invocation.getter(#blogPostRepository),
        ),
      ) as _i3.BlogPostRepository);

  @override
  _i7.Future<_i2.Result<List<_i8.BlogPost>>> execute(
          _i9.ReadAllBlogPostsParam? readAllBlogPostsParam) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [readAllBlogPostsParam],
        ),
        returnValue: _i7.Future<_i2.Result<List<_i8.BlogPost>>>.value(
            _FakeResult_0<List<_i8.BlogPost>>(
          this,
          Invocation.method(
            #execute,
            [readAllBlogPostsParam],
          ),
        )),
      ) as _i7.Future<_i2.Result<List<_i8.BlogPost>>>);
}

/// A class which mocks [CareerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCareerRepository extends _i1.Mock implements _i4.CareerRepository {
  MockCareerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Result<List<_i10.Career>>> readAllCareers() =>
      (super.noSuchMethod(
        Invocation.method(
          #readAllCareers,
          [],
        ),
        returnValue: _i7.Future<_i2.Result<List<_i10.Career>>>.value(
            _FakeResult_0<List<_i10.Career>>(
          this,
          Invocation.method(
            #readAllCareers,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Result<List<_i10.Career>>>);
}

/// A class which mocks [ReadAllCareersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadAllCareersUseCase extends _i1.Mock
    implements _i11.ReadAllCareersUseCase {
  MockReadAllCareersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.CareerRepository get careerRepository => (super.noSuchMethod(
        Invocation.getter(#careerRepository),
        returnValue: _FakeCareerRepository_2(
          this,
          Invocation.getter(#careerRepository),
        ),
      ) as _i4.CareerRepository);

  @override
  _i7.Future<_i2.Result<List<_i10.Career>>> execute(
          _i11.ReadAllCareersParam? readAllCareersParam) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [readAllCareersParam],
        ),
        returnValue: _i7.Future<_i2.Result<List<_i10.Career>>>.value(
            _FakeResult_0<List<_i10.Career>>(
          this,
          Invocation.method(
            #execute,
            [readAllCareersParam],
          ),
        )),
      ) as _i7.Future<_i2.Result<List<_i10.Career>>>);
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i5.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Result<List<_i12.Event>>> readAllEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #readAllEvents,
          [],
        ),
        returnValue: _i7.Future<_i2.Result<List<_i12.Event>>>.value(
            _FakeResult_0<List<_i12.Event>>(
          this,
          Invocation.method(
            #readAllEvents,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Result<List<_i12.Event>>>);
}

/// A class which mocks [ReadAllEventsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadAllEventsUseCase extends _i1.Mock
    implements _i13.ReadAllEventsUseCase {
  MockReadAllEventsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.EventRepository get eventRepository => (super.noSuchMethod(
        Invocation.getter(#eventRepository),
        returnValue: _FakeEventRepository_3(
          this,
          Invocation.getter(#eventRepository),
        ),
      ) as _i5.EventRepository);

  @override
  _i7.Future<_i2.Result<List<_i12.Event>>> execute(
          _i13.ReadAllEventsParams? readAllEventsParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [readAllEventsParams],
        ),
        returnValue: _i7.Future<_i2.Result<List<_i12.Event>>>.value(
            _FakeResult_0<List<_i12.Event>>(
          this,
          Invocation.method(
            #execute,
            [readAllEventsParams],
          ),
        )),
      ) as _i7.Future<_i2.Result<List<_i12.Event>>>);
}

/// A class which mocks [ProjectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectRepository extends _i1.Mock implements _i6.ProjectRepository {
  MockProjectRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Result<List<_i14.Project>>> readAllProjects() =>
      (super.noSuchMethod(
        Invocation.method(
          #readAllProjects,
          [],
        ),
        returnValue: _i7.Future<_i2.Result<List<_i14.Project>>>.value(
            _FakeResult_0<List<_i14.Project>>(
          this,
          Invocation.method(
            #readAllProjects,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Result<List<_i14.Project>>>);
}

/// A class which mocks [ReadAllProjectsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadAllProjectsUseCase extends _i1.Mock
    implements _i15.ReadAllProjectsUseCase {
  MockReadAllProjectsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ProjectRepository get projectRepository => (super.noSuchMethod(
        Invocation.getter(#projectRepository),
        returnValue: _FakeProjectRepository_4(
          this,
          Invocation.getter(#projectRepository),
        ),
      ) as _i6.ProjectRepository);

  @override
  _i7.Future<_i2.Result<List<_i14.Project>>> execute(
          _i15.ReadAllProjectsParam? readAllProjectsParam) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [readAllProjectsParam],
        ),
        returnValue: _i7.Future<_i2.Result<List<_i14.Project>>>.value(
            _FakeResult_0<List<_i14.Project>>(
          this,
          Invocation.method(
            #execute,
            [readAllProjectsParam],
          ),
        )),
      ) as _i7.Future<_i2.Result<List<_i14.Project>>>);
}
